# Generated by Django 6.0 on 2026-08-20 14:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('contact_info', models.TextField(help_text='Free-text contact details (phone, email, address, etc.).')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('ADJUSTMENT', 'Adjustment')], max_length=10)),
                ('product_sku', models.CharField(max_length=50)),
                ('location_info', models.CharField(help_text="Snapshot string, e.g. 'A-R01-B01'.", max_length=100)),
                ('quantity_shift', models.IntegerField(help_text='Signed change, e.g. +42 for inbound, -18 for outbound.')),
                ('resulting_quantity', models.PositiveIntegerField(help_text='Stock count in that bin immediately after this change.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(help_text="Short alphabetic zone code, e.g. 'A'. Stored uppercase automatically.", max_length=10, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', "Zone must contain letters only, e.g. 'A' or 'B' — no numbers or spaces.")])),
                ('rack', models.PositiveIntegerField(help_text="Rack number, 1 or greater. Stored as a plain number, not 'R01'.", validators=[django.core.validators.MinValueValidator(1)])),
                ('bin', models.PositiveIntegerField(help_text="Bin number, 1 or greater. Stored as a plain number, not 'B01'.", validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['zone', 'rack', 'bin'],
                'constraints': [models.UniqueConstraint(fields=('zone', 'rack', 'bin'), name='unique_location_zone_rack_bin')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('low_stock_threshold', models.PositiveIntegerField(default=0, help_text='Manager-defined threshold. When total quantity across all Locations falls at or below this number, the product should show up in low-stock reports/badges.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='warehouse.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='warehouse.supplier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField(help_text='Signed correction amount, e.g. -5 or +12. Can be negative.')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Set when a Manager approves/rejects.', null=True)),
                ('location', models.ForeignKey(help_text='Target bin where the discrepancy was found.', on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_requests', to='warehouse.location')),
                ('manager', models.ForeignKey(blank=True, help_text='Populated once a Manager approves or rejects this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_requests', to='warehouse.product')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='warehouse.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='warehouse.product')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'ordering': ['location', 'product'],
                'constraints': [models.UniqueConstraint(fields=('product', 'location'), name='unique_inventory_per_product_location')],
            },
        ),
    ]
