# Generated by Django 6.0 on 2026-08-26 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ADJUSTMENT_APPROVED', 'Adjustment Approved'), ('ADJUSTMENT_REJECTED', 'Adjustment Rejected'), ('ADJUSTMENT_SUBMITTED', 'Adjustment Submitted')], max_length=25)),
                ('message', models.CharField(max_length=255)),
                ('target_url', models.CharField(help_text='Where clicking this notification navigates to. Always generated server-side via reverse(), never user input.', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
