# Generated by Django 6.0 on 2026-08-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional profile photo. Falls back to initials if not set.', null=True, upload_to='profile_photos/'),
        ),
    ]
