# Generated by Django 6.0 on 2026-08-28 05:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional profile photo. Falls back to initials if not set.', null=True, upload_to=accounts.models.user_profile_photo_path),
        ),
    ]
