# Generated by Django 6.0 on 2026-08-29 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ADJUSTMENT_APPROVED', 'Adjustment Approved'), ('ADJUSTMENT_REJECTED', 'Adjustment Rejected'), ('ADJUSTMENT_SUBMITTED', 'Adjustment Submitted'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested')], max_length=25),
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='The Admin who reset or rejected this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_password_reset_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The account whose password reset was requested.', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
